### ISSUE TITLE
crashes when merged composer.json files have the same patch

### ISSUE THREAD

**Issue by joachim-n** [cweagans/composer-patches#241]
The plugin crashes with 'Array to string conversion' if different composer.json patches specify the same patch, due to this line:

```
      $this->io->write('    <info>' . $url . '</info> (<comment>' . $description. '</comment>)');
```

**Comment by joachim-n** [comment]
This is possibly the same issue as #224 which is fixed, but not in a stable release.

**Comment by alexdesignworks** [comment]
as of now, the latest release is 1.6.5 and it is still not fixed there.  There is a one-liner replacement required on line 118

```
$tmp_patches = $this->arrayMergeRecursiveDistinct($tmp_patches, $patches);
```

Is there any reason to not make a minor version release? Isn't this what the semantic versioning for?

**Comment by mike-potter** [comment]
Running into this also and would love to see a minor release.

**Comment by josephdpurcell** [comment]
Hopefully this context and workaround will help someone else.

## Problem

You may see an error on composer install like this:

```
Gathering patches for dependencies. This might take a minute.
  - Installing drupal/core (8.6.10): Loading from cache
  - Applying patches for drupal/core


  [ErrorException]
  Array to string conversion
```

This error may be related to having multiples of the same patch. (This might happen if using Drupal's Lightning distro with other modules or libraries that also apply patches to Drupal core.)

## What won't work

This is an issue with 1.6.5 still. Making a patch with https://github.com/cweagans/composer-patches/pull/224/files like so does NOT work:

```
      "patches": {
        "cweagans/composer-patches": {
          "prevent error when duplicate patches": "patches/composer_patches_multi_patch_error.patch"
        },
```

It appears the patch only takes affect on the second install/update (I assume on first install the code at runtime is unpatched).

## What will work

The following will work:

```
composer require cweagans/composer-patches:1.x-dev
```

Once https://github.com/cweagans/composer-patches/pull/224/commits/1b1011f16771f1f030e6751c472fa5bf88991a55 is in a tagged release this won't be needed.

**Comment by Cottser** [comment]
With [1.6.6 released](https://github.com/cweagans/composer-patches/releases/tag/1.6.6) this issue should be resolved.
