### ISSUE TITLE
[2.0.0-beta2] patching fails with `composer --no-cache`

### ISSUE THREAD

**Issue by temp** [cweagans/composer-patches#608]
### Verification

- [X] I have updated Composer to the most recent stable release (`composer self-update`)
- [X] I have updated Composer Patches to the most recent stable release (`composer update cweagans/composer-patches`)
- [X] I am using one of the supported PHP versions (8.0+)
- [X] I have searched existing issues _and_ discussions for my problem.
- [X] My problem is _not_ addressed in the [troubleshooting guide](https://docs.cweagans.net/composer-patches/troubleshooting/guide).

### What were you trying to do (and why)?

Build a frankenphp-based image. It calls `composer install --no-cache ...`

### What happened? What did you expect to happen?

```
  - Patching tecnickcom/tcpdf

In Downloader.php line 31:

  mkdir(): Not a directory

```

Problem is in Downloader.php, I guess the cache-dir from the composer config is null:
```
        $this->cacheDir = $composer->getConfig()->get('cache-dir') . '/patches';
        if (!is_dir($this->cacheDir)) {
            mkdir($this->cacheDir);
        }
```

So I guess either the cache-dir should be set to something temporary, or it should throw an error that it doesn't work with --no-cache, or caching should be disabled on --no-cache (don't know if this is possible).

### Full contents of `composer.json`

```shell
-
```

### Full contents of `patches.lock.json`

```shell
-
```

### Full output of `composer patches-doctor`

```shell
-
```

### Full output of relevant Composer command with the `-vvv` flag added

```shell
composer update --no-cache -vvv
```

**Comment by cweagans** [comment]
Having the cache available is definitely something that this plugin expects at the moment. I'd expect that the Composer downloader would handle this case on its own. I'll investigate that at some point.

In the shorter term, I'm wondering if the behavior of using `composer install --no-cache` is unique to your project. It appears that Frankenphp itself does not do that: https://github.com/search?q=repo%3Adunglas%2Ffrankenphp+composer+--no-cache&type=code

Are you supplying that argument in one of your build scripts?

**Comment by ALameLlama** [comment]
@cweagans A use cache for having --no-cache is a docker image. since you don't really plain on running the composer install command multiple times

```
COPY --from=composer:latest /usr/bin/composer /usr/local/bin/composer

COPY . /app
WORKDIR /app

ENV COMPOSER_ALLOW_SUPERUSER=1
RUN composer install --no-dev --prefer-dist --no-interaction --no-cache
```

**Comment by cweagans** [comment]
This was fixed in the linked PR.

**Comment by ALameLlama** [comment]
I'll double check the version I have installed but I was still getting this same error
